<?php
declare(strict_types=1);
// Editable interface copy. Defaults keep upgrades compatible with existing databases.
const SITE_TEXTS=[
    'header_contact'=>['Üst menü iletişim bağlantısı','Bize ulaşın'],
    'principle_1_title'=>['Birinci ilke başlığı','Mesleki özen'],
    'principle_1_text'=>['Birinci ilke açıklaması','Her ayrıntıda dikkatli bir yaklaşım'],
    'principle_2_title'=>['İkinci ilke başlığı','Hukuka bağlılık'],
    'principle_2_text'=>['İkinci ilke açıklaması','İlkelerimizle şekillenen çalışmalar'],
    'principle_3_title'=>['Üçüncü ilke başlığı','Açık iletişim'],
    'principle_3_text'=>['Üçüncü ilke açıklaması','Sürecin her aşamasında anlaşılır bilgi'],
    'intro_link'=>['Kurumsal tanıtım bağlantısı','Büromuz hakkında'],
    'all_practices'=>['Tüm çalışma alanları bağlantısı','Tüm çalışma alanları'],
    'all_articles'=>['Tüm yayınlar bağlantısı','Tüm yayınlar'],
    'read_article'=>['Yazı okuma bağlantısı','Yazıyı okuyun'],
    'practice_detail'=>['Alan detay bağlantısı','Detaylı bilgi'],
    'faq_eyebrow'=>['Sık sorulan sorular etiketi','MERAK EDİLENLER'],
    'faq_title'=>['Sık sorulan sorular başlığı','İlk adımı atarken.'],
    'faq_text'=>['Sık sorulan sorular açıklaması','Görüşme ve çalışma sürecine ilişkin sık sorulan sorular.'],
    'faq_link'=>['Sık sorulan sorular iletişim bağlantısı','Bizimle iletişime geçin'],
    'archive_title'=>['Makale arşivi başlığı',"Hukuku anlamak,\ndoğru adımla başlar."],
    'practice_archive_title'=>['Çalışma alanları sayfa başlığı',"Her meseleye,\nkendine özgü bir yaklaşım."],
    'search_title'=>['Arama penceresi başlığı','Hangi konuda bilgi arıyorsunuz?'],
    'search_placeholder'=>['Arama alanı ipucu','Örn. sözleşme, aile hukuku…'],
    'search_help'=>['Arama açıklaması','Çalışma alanları ve hukuki süreçler hakkında yayınlarımızı keşfedin.'],
    'sidebar_title'=>['Yan sütun iletişim başlığı',"Her meselenin\nbir hikâyesi var."],
    'sidebar_text'=>['Yan sütun iletişim açıklaması','Hukuki sürecinizi birlikte değerlendirelim.'],
    'contact_page_title'=>['İletişim sayfası başlığı','Birlikte değerlendirelim.'],
    'contact_info_title'=>['İletişim bilgileri başlığı','İletişimde kalalım.'],
    'contact_info_text'=>['İletişim bilgileri açıklaması','Görüşmek istediğiniz konuyu bize iletebilir, büromuzun iletişim bilgilerine buradan ulaşabilirsiniz.'],
    'contact_form_title'=>['Görüşme formu başlığı','Size nasıl ulaşalım?'],
    'contact_form_button'=>['Form gönderim butonu','Görüşme talebi gönder'],
    'contact_form_note'=>['Form altı açıklaması','Lütfen bu form üzerinden kimlik bilgileri veya hassas dosya ayrıntıları paylaşmayın. Form gönderimi tek başına avukatlık ilişkisi kurmaz.'],
    'footer_discover'=>['Alt menü başlığı','Önemli Bağlantılar'],
    'footer_practices'=>['Alt bilgi çalışma alanları başlığı','Çalışma Alanları'],
    'footer_contact'=>['Alt bilgi iletişim başlığı','Bize Ulaşın'],
    'footer_legal'=>['Alt bilgi yasal uyarı başlığı','Yasal Uyarı'],
    'hub_title'=>['Makaleler sayfası başlığı','Makaleler'],
    'hub_card_text'=>['Kategori kartı açıklaması ({kategori} yerine kategori adı gelir)','{kategori} makaleleri ve emsal karar arşivi için tıklayınız.'],
    'category_list_suffix'=>['Kategori sayfası başlık eki (boş bırakılabilir)','İle İlgili Yazılarımız'],
    'toc_title'=>['Makale içindekiler başlığı','İçindekiler'],
    'author_button'=>['Yazar kartı butonu','Hakkımda'],
    'recent_posts'=>['Son yazılar başlığı','Son Yazılar'],
    'same_category'=>['Aynı kategori başlığı','Aynı Kategoriden'],
    'updated_label'=>['Güncelleme etiketi','Güncelleme'],
];
function ui(string $key): string {return setting('text_'.$key,SITE_TEXTS[$key][1]??$key);}
