<?php declare(strict_types=1); ?>
<section class="hero">
    <img class="hero-image" src="<?=e(safe_image(setting('hero_image')))?>" alt="Adaleti simgeleyen terazi heykeli ve klasik mimari" width="1660" height="948" fetchpriority="high">
    <div class="hero-shade"></div>
    <div class="container hero-inner"><div class="hero-copy"><span class="eyebrow"><?=e(setting('hero_eyebrow'))?></span><h1><?=nl2br(e(setting('hero_title')))?></h1><p><?=e(setting('hero_text'))?></p><div class="hero-buttons"><a class="button button-glass" href="<?=e(safe_url(setting('hero_button_url')))?>"><?=e(setting('hero_button'))?> <?=icon('arrow-up')?></a><a class="hero-secondary" href="<?=e(safe_url(setting('hero_secondary_url')))?>"><?=e(setting('hero_secondary'))?> <?=icon('arrow')?></a></div></div><div class="hero-bottom"><span><?=e(setting('hero_note'))?></span><a href="#ana-icerik" aria-label="Tanıtım bölümüne ilerle">KEŞFEDİN <span>↓</span></a></div></div>
</section>
<div id="ana-icerik"></div>
<?php if(setting('show_intro')==='1'):?>
<section class="section introduction" id="yaklasim"><div class="container editorial-split"><div class="editorial-copy"><span class="eyebrow"><?=e(setting('intro_eyebrow'))?></span><h2><?=nl2br(e(setting('intro_title')))?></h2><div class="intro-text"><?=text_markup(setting('intro_text'))?></div><div class="intro-signoff"><span class="signature"><?=e(setting('brand'))?></span><span><?=e(setting('brand_subtitle'))?></span></div><a class="text-link" href="/kurumsal"><?=e(ui('intro_link'))?> <?=icon('arrow-up')?></a></div><figure class="editorial-visual"><img src="<?=e(safe_image(setting('intro_image')))?>" alt="Klasik mimaride sütunlar ve taş işçiliği" width="640" height="740" loading="lazy"><figcaption><strong><?=e(setting('intro_label'))?></strong><span><?=e(setting('intro_caption'))?></span></figcaption></figure></div></section>
<?php endif;if(setting('show_approach')==='1'):?>
<section class="section approach-section"><div class="container editorial-split reversed"><figure class="editorial-visual approach-visual"><img src="<?=e(safe_image(setting('approach_image')))?>" alt="Hukuk kütüphanesinde kitaplar" width="740" height="640" loading="lazy"></figure><div class="editorial-copy"><span class="eyebrow"><?=e(setting('approach_eyebrow'))?></span><h2><?=nl2br(e(setting('approach_title')))?></h2><div class="intro-text"><?=text_markup(setting('approach_text'))?></div><div class="principle-list"><?php foreach(['shield','scale','users'] as $i=>$symbol):?><div><?=icon($symbol)?><span><strong><?=e(ui('principle_'.($i+1).'_title'))?></strong><small><?=e(ui('principle_'.($i+1).'_text'))?></small></span></div><?php endforeach;?></div></div></div></section>
<?php endif;office_panel();if(setting('show_practices')==='1'):?>
<section class="section practices-section"><div class="container"><div class="section-heading centered"><span class="eyebrow"><?=e(setting('practice_eyebrow'))?></span><h2><?=nl2br(e(setting('practice_title')))?></h2><p><?=e(setting('practice_text'))?></p></div><div class="practice-photo-grid"><?php foreach(array_slice(entries('practice'),0,6) as $i=>$p)practice_photo($p,$i);?></div><div class="section-tail"><a class="button button-outline" href="/calisma-alanlari"><?=e(ui('all_practices'))?> <?=icon('arrow-up')?></a></div></div></section>
<?php endif;contact_band();if(setting('show_articles')==='1'):?>
<section class="section articles-section"><div class="container"><div class="section-heading"><div><span class="eyebrow"><?=e(setting('articles_eyebrow'))?></span><h2><?=e(setting('articles_title'))?></h2><p><?=e(setting('articles_text'))?></p></div><a class="text-link" href="/makaleler"><?=e(ui('all_articles'))?> <?=icon('arrow-up')?></a></div><div class="article-grid"><?php foreach(array_slice(entries('article'),0,3) as $a)article_card($a);?></div></div></section>
<?php endif;if(setting('show_faq')==='1'):?>
<section class="section faq-section" id="sik-sorulan-sorular"><div class="container faq-grid"><div><span class="eyebrow"><?=e(ui('faq_eyebrow'))?></span><h2><?=e(ui('faq_title'))?></h2><p><?=e(ui('faq_text'))?></p><a class="text-link" href="/iletisim"><?=e(ui('faq_link'))?> <?=icon('arrow-up')?></a></div><div class="faq-list"><?php foreach(entries('faq') as $i=>$f):?><details><summary><span class="faq-number"><?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></span><?=e($f['title'])?><span class="faq-plus">+</span></summary><div><?=text_markup($f['body'])?></div></details><?php endforeach;?></div></div></section>
<?php endif;?>
